- hosts: localhost
  become: true
  tasks:
    - name: Install packages
      apt:
        name:
          - htop
          - git
          - vim
          - maven
          - openvpn
        state: present
        autoclean: yes
