- name: Install packages
  apt:
    name:
      - htop
      - git
      - vim
      - maven
      - openvpn
      - python3
      - zsh
      - fonts-powerline # Fonts for the oh-my-zsh agnoster scheme
    state: present
    autoclean: yes
