- name: Install packages
  apt:
    name:
      - openjdk-11-jdk
      - htop
      - git
      - vim
      - maven
      - openvpn
      - resolvconf
      - python3
      - zsh
      - fonts-powerline # Fonts for the oh-my-zsh agnoster scheme
      # Packages for KVM and MiniShift
      - qemu-kvm
      - libvirt-daemon
      - libvirt-daemon-system
      - python-libvirt # Required for Ansible virt_net module
      - python-lxml    # Required for Ansible virt_net module
      - parallel       # Runs shell scripts in parallel
    state: present
    autoclean: yes
