- name: Clone oh-my-zsh
  become: false
  git:
    depth: 1
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    repo: https://github.com/robbyrussell/oh-my-zsh.git

- name: Set zsh as default shell
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: /bin/zsh

- name: Copy .zshrc
  copy:
    src: files/zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
